services:

  postgres:
    image: postgres:16
    container_name: rag-postgres
    restart: always

    environment:
      POSTGRES_DB: healthcare
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: rag-minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio-data:/data

  qdrant:
    image: qdrant/qdrant
    container_name: rag-qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  postgres-data:
  minio-data:
  qdrant-data: