# ==========================================
# Application Configuration
# ==========================================

spring.application.name=healthcare-backend

# ==========================================
# Server Configuration
# ==========================================

server.port=8080

# ==========================================
# Logging
# ==========================================

logging.level.root=INFO
logging.level.com.sohel.healthcare=DEBUG

# ==========================================
# PostgreSQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==========================================
# File Upload Configuration
# ==========================================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==========================================
# MinIO Configuration
# ==========================================

minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=documents

# ==========================================
# Qdrant Configuration
# ==========================================



# ==========================
# Gemini
# ==========================
gemini.api-key=${GEMINI_API_KEY}
gemini.chat-model=gemini-2.5-flash-lite
gemini.embedding-model=text-embedding-004

# ==========================
# Qdrant
# ==========================
qdrant.host=localhost
qdrant.port=6333
qdrant.collection=medical-documents